=== ClaudiaArguetaCaneza/xmlvalido_GRUPO03/Ejercicios/dtd_externa/tareas.dtd
<!--Grupo 3-->
<!ELEMENT universidad (grupodetrabajo, facultad, carrera, materia, grupo+)>
  <!ATTLIST universidad pertenencia CDATA #FIXED "Universidad de El Salvador">

  <!ELEMENT grupodetrabajo (#PCDATA)>

  <!ELEMENT facultad (nombref, codigof)>
  <!ELEMENT nombref (#PCDATA)>
  <!ELEMENT codigof (#PCDATA)>

  <!ELEMENT carrera (nombre, codigo)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT codigo (#PCDATA)>

  <!ELEMENT materia (#PCDATA)>

  <!ELEMENT grupo (formacion, profesor, evaluacion?, grupo_num, tema, integrantes)>
  <!ELEMENT formacion (#PCDATA)>
  <!ELEMENT profesor (#PCDATA)>
  <!ELEMENT evaluacion (actividad, porcentaje)?>
  <!ELEMENT actividad (#PCDATA)>
  <!ELEMENT porcentaje (#PCDATA)>

  <!ELEMENT grupo_num (#PCDATA)>
  <!ELEMENT tema (#PCDATA)>
  <!ELEMENT integrantes (integrante+)>

  <!ELEMENT integrante (carnet, ((nombresi,apellidos) | (apellidos,nombresi)), sexo?)>
  <!ELEMENT carnet (#PCDATA)>
  <!ELEMENT apellidos (#PCDATA)>
  <!ELEMENT nombresi (#PCDATA)>
  <!ELEMENT sexo (#PCDATA)>

  <!ATTLIST grupo_num
      tipo (GT | GL | GD) #REQUIRED
      aula (teorico | laboratorio | discusion) #REQUIRED>

  <!ATTLIST integrante
      coordinador (SI | NO) #REQUIRED>

=== ClaudiaArguetaCaneza/xmlvalido_GRUPO03/Ejercicios/dtd_externa/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE universidad SYSTEM "tareas.dtd">
<?xml-stylesheet type="text/css" href="tareas.css"?>
<!--Grupo #3-->
<universidad>
    <grupodetrabajo>El siguiente trabajo fue realizado por el grupo #3</grupodetrabajo>
    <facultad>
        <nombref>FIA</nombref>
        <codigof>FI001</codigof>
    </facultad>
    <carrera>
        <nombre>Ingeniería Informática</nombre>
        <codigo>II001</codigo>
    </carrera>
    <materia>Tecnicas de programacion para internet</materia>
    <grupo>
        <formacion>Teórico</formacion>
        <profesor>Ing. Balmore Ortiz</profesor>
        <grupo_num tipo="GT" aula="teorico">Grupo 3</grupo_num>
        <tema>XML valido</tema>
        <integrantes>
          <integrante coordinador="SI">
              <carnet>AC17033 </carnet>
              <apellidos>Claudia María </apellidos>
              <nombresi>Argueta Caneza</nombresi>
              <sexo>F</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>AL20006 </carnet>
              <nombresi>Helen Jazmín</nombresi>
              <apellidos> Alvarado Landaverde </apellidos>
              <sexo>F</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>BH18014 </carnet>
              <nombresi>Atlai Eliasib  </nombresi>
              <apellidos>Bonilla Henríquez  </apellidos>
              <sexo>M</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>EM19009  </carnet>
              <nombresi>Oscar Alejandro </nombresi>
              <apellidos>Elías Moran </apellidos>
              <sexo>M</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>MH18083   </carnet>
              <nombresi>Marvin Sigfredo </nombresi>
              <apellidos>Martínez Hernández </apellidos>
              <sexo>M</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>MH19028   </carnet>
              <nombresi>David Ernesto  </nombresi>
              <apellidos>Mendoza Herrera </apellidos>
              <sexo>M</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>OV14010 </carnet>
              <nombresi>Ángel Mauricio </nombresi>
              <apellidos>Ordoñez Vásquez  </apellidos>
              <sexo>M</sexo>
          </integrante>
          <integrante coordinador="NO">
              <carnet>RL18051 </carnet>
              <nombresi>Christian Adonay  </nombresi>
              <apellidos>Rivera López  </apellidos>
              <sexo>M</sexo>
          </integrante>
        </integrantes>
    </grupo>
</universidad>
